# Generated by Django 3.2.2 on 2021-05-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dea',
            name='horario_acceso',
            field=models.CharField(max_length=90),
        ),
    ]
