# Generated by Django 3.2.2 on 2021-05-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_alter_dea_horario_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='dea',
            name='direccion_codigo_postal',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='dea',
            name='direccion_via_codigo',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='dea',
            name='direccion_via_nombre',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
